### ISSUE TITLE
Documentation typo regarding file types

### ISSUE THREAD

**Issue by presentp** [Fraunhofer-IIS/camorph#10]
Dear

Could there be a typo in your documentation regarding file types?
![image](https://github.com/Fraunhofer-IIS/camorph/assets/141845311/6087f4cb-cb82-4937-9bb9-fda0e83aac75)
Which value should we use for Nerfs? Should be 'nerf' I guess?

Kind regards
Paulus

**Comment by bbrand-iis** [comment]
Yes, you're right! The key should of  course be 'nerf'

**Comment by bbrand-iis** [comment]
Fixed
