### ISSUE TITLE
Colmap to nerf image paths error and permissions error

### ISSUE THREAD

**Issue by henrypearce4D** [Fraunhofer-IIS/camorph#18]
Im getting this error when trying to run colmap to nerf. Image paths in my cameras.txt are set to the absolute paths, and I'm running conda as admin;

```
(camorph_win) d:\.repos\camorph>python -m camorph -i D:\.repos\camorph\in\txt\source -id D:/.repos/camorph/in/txt/images -if colmap -ft txt -o D:/.repos/camorph/out -of nerf
D:\.repos\camorph\camorph\ext\NeRF\NeRF.py:197: UserWarning: Camorph needs absolute image Paths. Relative paths are automatically calculated when saving to NeRF
  warnings.warn("Camorph needs absolute image Paths. Relative paths are automatically calculated when saving to NeRF")
Traceback (most recent call last):
  File "D:\.conda\envs\camorph_win\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\.conda\envs\camorph_win\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "d:\.repos\camorph\camorph\__main__.py", line 4, in <module>
    cli.run(run_as_module=True)
  File "D:\.repos\camorph\camorph\cli.py", line 58, in run
    camorph.write_cameras(cargs.output_format, cargs.output, cams, crop=c, scale=s, check_images=cargs.check_images,
  File "d:\.repos\camorph\camorph\camorph.py", line 119, in write_cameras
    dest_inst.write_file(cam_copy, path, file_type)
  File "D:\.repos\camorph\camorph\ext\NeRF\NeRF.py", line 225, in write_file
    with open(output_path, 'w') as f:
PermissionError: [Errno 13] Permission denied: 'D:/.repos/camorph/out'
```

**Comment by bbrand-iis** [comment]
Hi,

This is because you are trying to write to the **file** D:/.repos/camorph/out which is in all likelyhood a directory. You need to specify the json name in the output path, i.e. D:/.repos/camorph/out/tansforms.json

This could be a more verbose error message, you are right :)

**Comment by henrypearce4D** [comment]
Hi thanks, that makes sense.

When adding the filename "transforms.json"  it does save now, but I get an error and the image paths in the .json are incorrect;

error
```
(camorph_win) d:\.repos\camorph>python -m camorph -i D:\.repos\camorph\in\txt\source -id D:/.repos/camorph/in/txt/images -if colmap -ft txt -o D:/.repos/camorph/out/transforms.json -of nerf
D:\.repos\camorph\camorph\ext\NeRF\NeRF.py:197: UserWarning: Camorph needs absolute image Paths. Relative paths are automatically calculated when saving to NeRF
  warnings.warn("Camorph needs absolute image Paths. Relative paths are automatically calculated when saving to NeRF")
```
filepath in .json
`            "file_path": "..\\in\\txt\\images\\0001.png",`

I defined the image directory with;
`-id D:/.repos/camorph/in/txt/images`

Also as a test I made an edit to the images.txt to include the paths just in case but that didn't work.

**Comment by bbrand-iis** [comment]
Hi,

This is not an error, but a warning. The transforms.json file should still be there. 
This warning is because camorph usually operates on absolute file paths (i.e. D:/.repos/camorph/in/txt/images/0001.png), but when saving to NeRF format it automatically caluclates relative file pahts (i.e. ../in/txt/images/0001.png). As this is just a warning you can safely ignore that. The reason for this warning is to avoid any confusion when working with relative and absolute data paths in your workflow.

Edit: I just read that it saves fine. When camorph saves a file, you can safely assume that everything went right.
